# Generated by Django 3.1.7 on 2021-03-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ido', models.CharField(default='', max_length=300)),
                ('user_idO', models.CharField(default='', max_length=300)),
                ('amount', models.IntegerField(default=0)),
                ('coins_balance', models.IntegerField(default=0)),
                ('txn_type', models.CharField(default='', max_length=300)),
                ('txn_info', models.CharField(default='', max_length=300)),
                ('action', models.CharField(default='', max_length=300)),
                ('time', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
